name: i_am_rich
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
     - images/avatar.jpg
  fonts:
    - family: TiltNeon
      fonts:
        - asset: fonts/TiltNeon-Regular-VariableFont_XROT,YROT.ttf
    - family: Inspiration
      fonts:
        - asset: fonts/Inspiration-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: RobotoMono-Italic
      fonts:
        - asset: fonts/RobotoMono-Italic-VariableFont_wght.ttf
    - family: RobotoMono-VariableFont
      fonts:
        - asset: fonts/RobotoMono-VariableFont_wght.ttf


